### ISSUE TITLE
Usage with ecto

### ISSUE THREAD

**Issue by briankariuki** [feng19/spider_man#3]
I want to save the resulting items in a database instead of ets/csv e.t.c.

How can I do this?

**Comment by feng19** [comment]
You can implement a [storage](https://github.com/feng19/spider_man/blob/master/lib/spider_man/storage/storage.ex) like [this](https://github.com/feng19/spider_man/blob/master/lib/spider_man/storage/log.ex)

use ecto to save items in `store/3`

**Comment by briankariuki** [comment]
@feng19 Thanks
