### ISSUE TITLE
When Spider fails it prevents further execution in iex

### ISSUE THREAD

**Issue by briankariuki** [feng19/spider_man#4]
I run a spider using Spider.run(). If it encounters an error in parsing the content, it blocks the iex console and no further commands can be carried out.

I expect it to return an error and stop execution.

<img width="1161" alt="image" src="https://github.com/feng19/spider_man/assets/34672053/73dd2bee-b84f-4ea4-ba71-440f8bd1f94c">

Also how would I go about setting up a spider in a production environment. I'm thinking of using a genserver to call Spider.run() multiple times a day. One drawback is that I wouldn't know if the run was succesful or not as Spider.run() does not return a result to the caller.

**Comment by feng19** [comment]
You can start the spider use `SpiderMan.start(YourSpiderModule, settings)` instead of `YourSpiderModule.run()`
maybe you need more [functions](https://hexdocs.pm/spider_man/SpiderMan.html#functions) to control the spider.
